---
language: python
sudo: required
dist: trusty
cache:
  directories: [ '$HOME/lxc' ]
  pip: true
env:
- LXC_DISTRO=debian LXC_RELEASE=wheezy
- LXC_DISTRO=debian LXC_RELEASE=jessie
- LXC_DISTRO=debian LXC_RELEASE=stretch
- LXC_DISTRO=ubuntu LXC_RELEASE=trusty
- LXC_DISTRO=ubuntu LXC_RELEASE=xenial
- LXC_DISTRO=centos LXC_RELEASE=6
- LXC_DISTRO=centos LXC_RELEASE=7
before_cache:
- 'sudo mkdir $HOME/lxc && sudo tar cf $HOME/lxc/cache.tar /var/cache/lxc/ &&
  sudo chown $USER: $HOME/lxc/cache.tar'
install:
- sudo tar xf $HOME/lxc/cache.tar -C / || true
- sudo apt-get install -y expect-dev
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../\ncallback_whitelist=profile_tasks' >ansible.cfg
- ansible-galaxy install lae.travis-lxc
- ansible-playbook -vvv tests/install.yml -i tests/inventory
script:
- ansible-playbook tests/deploy.yml -i tests/inventory --syntax-check
- ansible-playbook tests/deploy.yml -i tests/inventory
- 'ANSIBLE_STDOUT_CALLBACK=debug unbuffer ansible-playbook -vv tests/deploy.yml
  -i tests/inventory >/tmp/idempotency.log 2>&1 ||
  (e=$?; cat /tmp/idempotency.log; exit $e)'
- 'grep -A1 "PLAY RECAP" /tmp/idempotency.log | grep -qP "changed=0.*failed=0" &&
  (echo "Idempotence: PASS"; exit 0) ||
  (echo "Idempotence: FAIL"; cat /tmp/idempotency.log; exit 1)'
- ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook -v tests/test.yml -i tests/inventory
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: sP7LViTCMytGhIPI9qDrJ8aCWmG+DG1/egtdCDHSaeSWi60Dplev2UK5emrNDd1jD+dtixC6qv3z0A8sSLTJJA2/0EZONpfUX3imq4zGcxaTKOtQ2moNpWusTc8chHnpvQPy9k00PLaRRmr04PwQgDyUtQ4WrtRPYhL40VJRNQHukmiecHv4P3UMs3YPiENZow6OYgSL1+9hBseu2rrwFP43sBvfKvTchR6nwCQjtn4HrrbUcF0ydiQcRHqaQ+GLeWX7ZTT2dwcw2fTSBEfLwNwdToEky8FuDa7MIhszQ6MyHLfd7ABpWAwvOsjfyR0GkKtjbOo10XkgIfMzvizyDZg+gNvZYtBo/1JQtyRWPdj73Y1nxWbu+jx+F2WmuMNZf6zMrOrEC95eZAKY30Elm6B64mBkanfKqwlxcg06IluRa5syUvFvbTThXgrOhS5xcKDL4guklPvvW5D3vKugFk00YwK/3shK78yjsKAFN1H7hqgn3EXzIaD32NlghInDTsB6m7aFUUA+Y6wgZB1i2vtN9OMYoLcQTPFZeg292D5DJup5urREn6kMj83FiA5cza9zRew7aOu0YWBTOBr4WveanyCbnCBQ7C8mSA+wIVoYXf2FHrhriaZbzsYjpOtzcioMnvYiJoiUzpEY8lxoiLcScXcIbX0y6sW5/4C2hkc=
