---
# tasks file for base
- name: "Gather OS specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

- name: Ensure profile.d exists
  file:
    path: /etc/profile.d
    state: directory
    mode: 0755

- name: Install bash environment scripts into profile.d
  copy:
    src: "{{ item }}"
    dest: "/etc/profile.d/{{ item }}"
    mode: 0755
  with_items:
    - history.sh
    - aliases.sh
    - fixterm.sh

- name: Install packf and unpackf
  copy:
    src: "{{ item }}"
    dest: "/usr/bin/{{ item }}"
    mode: 0755
  with_items:
    - packf
    - unpackf

- set_fact:
    __base_packages: "{{ base_required_packages }}+{{ base_packages }}"

- name: Install base packages
  package:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: "{{ __base_packages }}"

- name: Ensure public IP is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
    regexp: "{{ ansible_hostname }}"
  when: base_edit_hosts

- include_tasks: configure_sysstat.yml

# vim:ft=ansible:
