---
- name: Copy sysstat configuration
  copy:
    src: sysstat
    dest: /etc/sysstat/sysstat
    mode: 0644

- name: Enable sysstat in config
  lineinfile:
    dest: /etc/default/sysstat
    state: present
    line: "ENABLED='true'"
    regexp: "^ENABLED="
